# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_kits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyiticsKitsMixin',
        ),
    ]
